### ISSUE TITLE
Column 'dG(kcal/mol)' not exist in PPB-Affinity.xlsx

### ISSUE THREAD

**Issue by FsheriF** [ChenPy00/PPB-Affinity#1]
Dear Author

Thanks for provide such important resource, I very enjoy read your paper published in Scientific Data.

I want to follow your document to process data and train the base-line model. However, when I run the "process_data.py", it showed an error that `ValueError: Usecols do not match columns, columns expected but not found: ['dG(kcal/mol)']`. I check the PPB-Affinity.xlsx, it indeed not contain the dG(kcal/mol) column but the "KD(M)".

Could you kind fix the PPB-Affinity.xlsx file? Many thanks!

**Comment by ChenPy00** [comment]
Thank you for discovering the bug. 

dG can be calculated using this equation: ```dG = RT ln(KD)```，where **R** is universal gas constant, **T** is temperature, ```ln()``` is the natural logarithm. In this work, we used ```(8.314/4184)*(273.15 + 25.0) * ln(KD)``` to calculate dG, but you can calculate the corresponding dG from the temperatures in PPB-Affinity.xlsx.

We have added a step to calculate dG in the "process_data.py" and hope it solves your problem.

**Comment by FsheriF** [comment]
Thanks for your kind reply, I just modified the information from your demo benchmark.csv.
