### ISSUE TITLE
After training, how to use the trained model to predict new PDB file?

### ISSUE THREAD

**Issue by FsheriF** [ChenPy00/PPB-Affinity#2]
I followed your document and run the "train.py" by default setting in one 4090 and it ran around 6 hours.

It successfully form 100 checkpoints file from 1000.pt to 100000.pt. I wonder how to apply this model into my own PDB complex file.

1. Which pt file should I used, 100000.pt? 
2. What's the main function or code should I call？
3. The PDB file should do any other process before input in to PPB-Affinity？

Waiting for your kind replay.

Thanks in advance.

**Comment by ChenPy00** [comment]
Thanks for your message! Here are my responses to your questions:

Q1: To select the appropriate file for your needs, I recommend monitoring changes during the training process, such as correlation metrics and signs of overfitting.

Q2 & Q3: I have uploaded an inference script, "inference.py," which includes functionality for processing PDB files and performing model inference. This should assist you in predicting outcomes for your personal files. Additionally, I've provided sample data for inference, so feel free to modify it as needed to suit your requirements!

I hope this addresses your concerns!

Feel free to adjust any part of it further if needed!
