### ISSUE TITLE
sharing checkpoint.pt

### ISSUE THREAD

**Issue by QUEST2179** [ChenPy00/PPB-Affinity#3]
when I ran train.py, it first gave a warning divisonzero when processing data, then after a few steps of training, the program got killed silently. Is it possible sharing checkpoint.pt since I am more interested in prediction outcome?  Thanks!

**Comment by ChenPy00** [comment]
Of course, we have uploaded trained weight on the [Hugging Face](https://huggingface.co/ChenPy00/PPB-Affinity), which includes `checkpoint.pt` and `result.csv`.

We provide the images in the `CrossValidationFigs` folder, which were drawn using the `result.csv`
